server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crud
    username: fuad
    password: esscsmfu2
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update